# Generated by Django 4.1.3 on 2022-12-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection (title) VALUES ('colletion1')
        """, """
        DELETE FROM store_collection WHERE title='collection1'
        """)
    ]
