# Generated by Django 4.1.3 on 2022-12-20 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='products',
        ),
        migrations.AddField(
            model_name='products',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='store.promotion'),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
